# Generated by Django 3.2.8 on 2021-11-07 08:47

import autoslug.fields
from django.db import migrations, models
import trip.models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='Slug',
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from=trip.models.get_slug),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='Statu',
            field=models.CharField(blank=True, default='publish', max_length=50),
        ),
    ]
