# Generated by Django 3.2.8 on 2021-11-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20211107_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
