# Generated by Django 3.2.8 on 2021-11-04 05:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, default='Start and end in San Francisco! With the in-depth cultural .', null=True),
        ),
    ]
