# Generated by Django 3.2.8 on 2021-11-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0002_alter_hotel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Banner_Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Facilities',
            field=models.ManyToManyField(blank=True, null=True, to='Hotels.Facilities'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Gallery',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Hotel_service',
            field=models.ManyToManyField(blank=True, null=True, to='Hotels.Hotel_service'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Property_type',
            field=models.ManyToManyField(blank=True, null=True, to='Hotels.Property_type'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_attribute',
            field=models.ManyToManyField(blank=True, null=True, to='Hotels.Attribute'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
