# Generated by Django 3.2.8 on 2021-11-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0003_auto_20211104_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Facilities',
            field=models.ManyToManyField(to='Hotels.Facilities'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Hotel_service',
            field=models.ManyToManyField(to='Hotels.Hotel_service'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Property_type',
            field=models.ManyToManyField(to='Hotels.Property_type'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_attribute',
            field=models.ManyToManyField(to='Hotels.Attribute'),
        ),
    ]
